### ISSUE TITLE
How to run on client side???

### ISSUE THREAD

**Issue by sujjeee** [mmo80/pdfja-nextjs-bug#1]
Hey @mmo80  

 I'm trying to use pdfjs-dist in my Next.js app.

This is essentially a function:

this is basically a function
```javascript
import * as pdfjsLib from "pdfjs-dist";

export async function crop(pdfBuffer: ArrayBuffer) {
  const pdfDoc: PDFDocumentProxy = await pdfjsLib.getDocument(pdfBuffer).promise;
  // other code 
}
 ```
I'm calling this function when a button is clicked, but before that, I'm getting this error:

`Error: Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.`

Please let me know if you have any solutions to fix this issue.

**Comment by mmo80** [comment]
> Hey @mmo80
> 
> I'm trying to use pdfjs-dist in my Next.js app.
> 
> This is essentially a function:
> 
> this is basically a function
> 
> ```js
> import * as pdfjsLib from "pdfjs-dist";
> 
> export async function crop(pdfBuffer: ArrayBuffer) {
>   const pdfDoc: PDFDocumentProxy = await pdfjsLib.getDocument(pdfBuffer).promise;
>   // other code 
> }
> ```
> 
> I'm calling this function when a button is clicked, but before that, I'm getting this error:
> 
> `Error: Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.`
> 
> Please let me know if you have any solutions to fix this issue.

Have not tried it on client-side. Only server-side. Did you get it working?

**Comment by sujjeee** [comment]
@mmo80 just using it with script
