### ISSUE TITLE
TypeError: Promise.withResolvers

### ISSUE THREAD

**Issue by Jwiggiff** [mmo80/pdfja-nextjs-bug#2]
Hey! I have been trying to get this to work for so long and your code was a huge help. I ran your project and it worked perfectly, but for some reason when I copy your `route.ts` into mine, I run into this error: `TypeError: Promise.withResolvers is not a function`. This has been my blocker for so long I'm wondering if you have any idea or if you fixed this yourself?

EDIT: Here's a minimal [example](https://codesandbox.io/p/devbox/compassionate-greider-tlywgt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv45q2mx0006356i0y4vs4cd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv45q2mx0002356is9l15rb2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv45q2mx0004356imoqurq3y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv45q2mx0005356i6twn3sdq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv45q2mx0002356is9l15rb2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv45q2mx0001356isveya0wc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clv45q2mx0002356is9l15rb2%2522%252C%2522activeTabId%2522%253A%2522clv45q2mx0001356isveya0wc%2522%257D%252C%2522clv45q2mx0005356i6twn3sdq%2522%253A%257B%2522id%2522%253A%2522clv45q2mx0005356i6twn3sdq%2522%252C%2522activeTabId%2522%253A%2522clv45tbed00fi356i7jlalmz7%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clv45tbed00fi356i7jlalmz7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clv45q2mx0004356imoqurq3y%2522%253A%257B%2522id%2522%253A%2522clv45q2mx0004356imoqurq3y%2522%252C%2522activeTabId%2522%253A%2522clv4623ey01cr356if9h89tpt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%252C%2522id%2522%253A%2522clv45sv1k00b8356i8dquoq1l%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clv4623ey01cr356if9h89tpt%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with the error

**Comment by mmo80** [comment]
Seems to have to do with the newer version of `"pdfjs-dist": "^4.1.392"` that you use. I updated to that version and got the same error. I would suggest to just use `"pdfjs-dist": "4.0.379"` (lock the specific version by removing the `^`... and run `npm update` to update to that specific version) to get it working. And try to figure out what breaking change they did later 😸

**Comment by mmo80** [comment]
Was related to the newer version of `pdfjs-dist`. Would suggest to lock to version `4.0.379` to get it working as per this repo.
